import type { WorldData } from "../src/server/worlds/data";

/**
 * Verified public data for the Proof landing examples.
 * Snapshot: 2026-07-15 (GitHub GraphQL/REST APIs).
 * Empty optional fields are intentionally omitted instead of guessed.
 */
export const EXAMPLE_DATA = {
  "torvalds-terminal": {
    identity: {
      name: "Linus Torvalds",
      handle: "torvalds",
      role: "Linux kernel maintainer",
      headline: "Creator of Linux and Git.",
      location: "Portland, OR",
      available: false,
    },
    tagline: "Maintaining the kernel at the center of modern computing.",
    email: "",
    links: { github: "https://github.com/torvalds" },
    stats: { contributionsPastYear: 3218, publicRepos: 9, featuredBuilds: 4, buildingSince: 2011 },
    stack: ["C", "OpenSCAD"],
    primaryStack: "C",
    disciplines: [["Operating systems", "Kernel engineering"], ["Version control", "Git"], ["Hardware", "Audio and circuits"]],
    projects: [
      { name: "linux", year: 2026, tech: ["C"], stars: 239424, repoUrl: "https://github.com/torvalds/linux", blurb: "Linux kernel source tree." },
      { name: "AudioNoise", year: 2026, tech: ["C"], stars: 4431, repoUrl: "https://github.com/torvalds/AudioNoise", blurb: "Random digital audio effects." },
      { name: "uemacs", year: 2026, tech: ["C"], stars: 2085, repoUrl: "https://github.com/torvalds/uemacs", blurb: "A personal version of MicroEMACS with private modifications." },
      { name: "GuitarPedal", year: 2026, tech: ["C"], stars: 2083, repoUrl: "https://github.com/torvalds/GuitarPedal", blurb: "An exploration of analog circuits through guitar-pedal design." },
    ],
    experience: [],
    credentials: [],
  },
  "karpathy-neural-dither": {
    identity: {
      name: "Andrej Karpathy",
      handle: "karpathy",
      role: "AI researcher and educator",
      headline: "Training neural networks and teaching how they work.",
      location: "Stanford",
      available: false,
    },
    tagline: "Neural networks, language models, education and research systems.",
    email: "",
    links: { github: "https://github.com/karpathy", site: "https://karpathy.ai" },
    stats: { contributionsPastYear: 892, publicRepos: 54, featuredBuilds: 4, buildingSince: 2010 },
    stack: ["Python", "CUDA", "C", "PyTorch"],
    primaryStack: "Python",
    disciplines: [["AI research", "Neural networks"], ["Education", "Technical courses"], ["Systems", "Model training"]],
    projects: [
      { name: "autoresearch", year: 2026, tech: ["Python"], stars: 91063, repoUrl: "https://github.com/karpathy/autoresearch", blurb: "AI agents running research on single-GPU nanochat training automatically." },
      { name: "nanoGPT", year: 2025, tech: ["Python"], stars: 61154, repoUrl: "https://github.com/karpathy/nanoGPT", blurb: "A simple, fast repository for training and fine-tuning medium-sized GPTs." },
      { name: "nanochat", year: 2026, tech: ["Python"], stars: 56247, repoUrl: "https://github.com/karpathy/nanochat", blurb: "A compact end-to-end ChatGPT implementation designed around a $100 training run." },
      { name: "LLM101n", year: 2024, tech: [], stars: 37469, repoUrl: "https://github.com/karpathy/LLM101n", blurb: "A course project for building an LLM-based storyteller from first principles." },
    ],
    experience: [],
    credentials: [],
  },
  "gaearon-magazine": {
    identity: {
      name: "Dan Abramov",
      handle: "gaearon",
      role: "Software engineer and writer",
      headline: "Building and explaining user interfaces.",
      location: "",
      available: false,
    },
    tagline: "React, JavaScript, interface engineering and technical writing.",
    email: "",
    links: { github: "https://github.com/gaearon", site: "https://overreacted.io" },
    stats: { contributionsPastYear: 755, publicRepos: 60, featuredBuilds: 4, buildingSince: 2011 },
    stack: ["JavaScript", "TypeScript", "CSS", "React"],
    primaryStack: "JavaScript",
    disciplines: [["Interfaces", "React"], ["Writing", "Software education"], ["Tooling", "Developer experience"]],
    projects: [
      { name: "react-hot-loader", year: 2023, tech: ["JavaScript", "React"], stars: 12174, repoUrl: "https://github.com/gaearon/react-hot-loader", blurb: "Real-time React component editing, now superseded by Fast Refresh." },
      { name: "overreacted.io", year: 2026, tech: ["TypeScript"], stars: 7273, repoUrl: "https://github.com/gaearon/overreacted.io", demoUrl: "https://overreacted.io", blurb: "The source for Dan Abramov's personal software-development publication." },
      { name: "react-hot-boilerplate", year: 2020, tech: ["JavaScript", "React"], stars: 3890, repoUrl: "https://github.com/gaearon/react-hot-boilerplate", blurb: "A minimal live-editing example for React." },
      { name: "react-transform-boilerplate", year: 2020, tech: ["JavaScript", "React", "Webpack"], stars: 3335, repoUrl: "https://github.com/gaearon/react-transform-boilerplate", blurb: "A Webpack boilerplate for hot reloading and component-level error handling." },
    ],
    experience: [],
    credentials: [],
  },
  "rauchg-liquid-chrome-monolith": {
    identity: {
      name: "Guillermo Rauch",
      handle: "rauchg",
      role: "Founder and CEO, Vercel",
      headline: "Building the platform for the web's next ideas.",
      location: "San Francisco",
      available: false,
    },
    tagline: "Web infrastructure, deployment systems and developer experience.",
    email: "",
    links: { github: "https://github.com/rauchg", site: "https://rauchg.com" },
    stats: { contributionsPastYear: 86, publicRepos: 64, featuredBuilds: 4, buildingSince: 2008 },
    stack: ["JavaScript", "TypeScript", "Shell", "MDX"],
    primaryStack: "JavaScript",
    disciplines: [["Web infrastructure", "Deployment"], ["Products", "Developer platforms"], ["Open source", "Web tooling"]],
    projects: [
      { name: "slackin", year: 2023, tech: ["JavaScript"], stars: 6500, repoUrl: "https://github.com/rauchg/slackin", blurb: "A tool that makes public Slack organizations easy to join." },
      { name: "wifi-password", year: 2024, tech: ["Shell"], stars: 4554, repoUrl: "https://github.com/rauchg/wifi-password", blurb: "A Bash utility for retrieving the password of the current Wi-Fi network." },
      { name: "blog", year: 2026, tech: ["MDX"], stars: 1419, repoUrl: "https://github.com/rauchg/blog", demoUrl: "https://rauchg.com", blurb: "The source for Guillermo Rauch's personal site and writing." },
      { name: "spot", year: 2024, tech: ["Shell"], stars: 955, repoUrl: "https://github.com/rauchg/spot", blurb: "A tiny file-search utility written in Bash." },
    ],
    experience: [],
    credentials: [],
  },
  "yyx990803-neural-chromatic": {
    identity: {
      name: "Evan You",
      handle: "yyx990803",
      role: "Founder and CEO, VoidZero",
      headline: "Author of Vue and Vite. Building unified JavaScript tooling.",
      location: "Singapore",
      available: false,
    },
    tagline: "JavaScript frameworks, build tools and high-performance developer infrastructure.",
    email: "",
    links: { github: "https://github.com/yyx990803", site: "https://evanyou.me", x: "https://x.com/evanyou" },
    stats: { contributionsPastYear: 2148, publicRepos: 75, featuredBuilds: 4, buildingSince: 2010 },
    stack: ["TypeScript", "JavaScript", "Rust", "HTML"],
    primaryStack: "TypeScript",
    disciplines: [["Frameworks", "Vue"], ["Build tooling", "Vite and Rolldown"], ["Performance", "Rust tooling"]],
    projects: [
      { name: "vite", year: 2026, tech: ["TypeScript"], stars: 82058, repoUrl: "https://github.com/vitejs/vite", demoUrl: "https://vite.dev", blurb: "Next-generation frontend tooling focused on speed." },
      { name: "core", year: 2026, tech: ["TypeScript", "Vue"], stars: 53952, repoUrl: "https://github.com/vuejs/core", demoUrl: "https://vuejs.org", blurb: "The core of Vue, a progressive framework for building web interfaces." },
      { name: "oxc", year: 2026, tech: ["Rust"], stars: 21951, repoUrl: "https://github.com/oxc-project/oxc", demoUrl: "https://oxc.rs", blurb: "A collection of high-performance JavaScript tools written in Rust." },
      { name: "rolldown", year: 2026, tech: ["Rust", "TypeScript"], stars: 13942, repoUrl: "https://github.com/rolldown/rolldown", demoUrl: "https://rolldown.rs", blurb: "A fast Rust bundler with a Rollup-compatible API." },
    ],
    experience: [],
    credentials: [],
  },
  "sindresorhus-digital-loom": {
    identity: {
      name: "Sindre Sorhus",
      handle: "sindresorhus",
      role: "Full-time open-source developer",
      headline: "Making macOS apps, CLI tools and focused packages.",
      location: "",
      available: false,
    },
    tagline: "Swift, JavaScript, TypeScript and more than a thousand maintained packages.",
    email: "",
    links: { github: "https://github.com/sindresorhus", site: "https://sindresorhus.com" },
    stats: { contributionsPastYear: 4442, publicRepos: 1129, featuredBuilds: 4, buildingSince: 2009 },
    stack: ["Swift", "JavaScript", "TypeScript", "Node.js"],
    primaryStack: "Swift",
    disciplines: [["Open source", "Package ecosystems"], ["Applications", "macOS and iOS"], ["Tooling", "CLI utilities"]],
    projects: [
      { name: "awesome", year: 2026, tech: [], stars: 484816, repoUrl: "https://github.com/sindresorhus/awesome", blurb: "A curated collection of useful lists across technology and culture." },
      { name: "type-fest", year: 2026, tech: ["TypeScript"], stars: 17297, repoUrl: "https://github.com/sindresorhus/type-fest", blurb: "A collection of essential TypeScript types." },
      { name: "ky", year: 2026, tech: ["TypeScript", "JavaScript"], stars: 16986, repoUrl: "https://github.com/sindresorhus/ky", blurb: "A tiny, elegant HTTP client based on the Fetch API." },
      { name: "quick-look-plugins", year: 2026, tech: [], stars: 18695, repoUrl: "https://github.com/sindresorhus/quick-look-plugins", blurb: "A maintained list of useful Quick Look plugins for developers." },
    ],
    experience: [],
    credentials: [],
  },
  "tiangolo-living-blueprint": {
    identity: {
      name: "Sebastián Ramírez",
      handle: "tiangolo",
      role: "Open-source software developer",
      headline: "Creator of FastAPI, Typer, SQLModel and Asyncer.",
      location: "Berlin, Germany",
      available: false,
    },
    tagline: "Python APIs, developer tools, data systems and AI infrastructure.",
    email: "",
    links: { github: "https://github.com/tiangolo", site: "https://tiangolo.com", x: "https://x.com/tiangolo" },
    stats: { contributionsPastYear: 5691, publicRepos: 41, featuredBuilds: 4, buildingSince: 2012 },
    stack: ["Python", "Type hints", "SQL", "Docker"],
    primaryStack: "Python",
    disciplines: [["APIs", "FastAPI"], ["Developer tools", "Typed CLIs"], ["Data systems", "SQLModel"]],
    projects: [
      { name: "fastapi", year: 2026, tech: ["Python"], stars: 100469, repoUrl: "https://github.com/fastapi/fastapi", demoUrl: "https://fastapi.tiangolo.com", blurb: "A high-performance Python API framework designed for production." },
      { name: "typer", year: 2026, tech: ["Python"], stars: 19750, repoUrl: "https://github.com/fastapi/typer", demoUrl: "https://typer.tiangolo.com", blurb: "A library for building command-line applications from Python type hints." },
      { name: "sqlmodel", year: 2026, tech: ["Python", "SQL"], stars: 18187, repoUrl: "https://github.com/fastapi/sqlmodel", demoUrl: "https://sqlmodel.tiangolo.com", blurb: "Python SQL databases designed for simplicity, compatibility and robustness." },
      { name: "asyncer", year: 2026, tech: ["Python", "AsyncIO"], stars: 2471, repoUrl: "https://github.com/fastapi/asyncer", demoUrl: "https://asyncer.tiangolo.com", blurb: "Async and await utilities focused on developer experience." },
    ],
    experience: [],
    credentials: [],
  },
  "simonw-signal-studio": {
    identity: {
      name: "Simon Willison",
      handle: "simonw",
      role: "Independent open-source developer",
      headline: "Building tools for data, SQLite and language models.",
      location: "Half Moon Bay, California",
      available: false,
    },
    tagline: "Creator of Datasette and co-creator of Django, exploring data and LLM tooling.",
    email: "",
    links: { github: "https://github.com/simonw", site: "https://simonwillison.net", x: "https://x.com/simonw" },
    stats: { contributionsPastYear: 6890, publicRepos: 639, featuredBuilds: 4, buildingSince: 2008 },
    stack: ["Python", "SQLite", "HTML", "JavaScript"],
    primaryStack: "Python",
    disciplines: [["Data", "Datasette and SQLite"], ["AI", "LLM tooling"], ["Publishing", "Open data"]],
    projects: [
      { name: "llm", year: 2026, tech: ["Python", "LLMs"], stars: 12184, repoUrl: "https://github.com/simonw/llm", demoUrl: "https://llm.datasette.io", blurb: "A command-line and Python library for accessing large language models." },
      { name: "datasette", year: 2026, tech: ["Python", "SQLite"], stars: 11276, repoUrl: "https://github.com/simonw/datasette", demoUrl: "https://datasette.io", blurb: "An open-source multi-tool for exploring and publishing data." },
      { name: "files-to-prompt", year: 2025, tech: ["Python"], stars: 2757, repoUrl: "https://github.com/simonw/files-to-prompt", blurb: "A utility that concatenates a directory of files into a prompt." },
      { name: "shot-scraper", year: 2026, tech: ["Python", "Playwright"], stars: 2508, repoUrl: "https://github.com/simonw/shot-scraper", demoUrl: "https://shot-scraper.datasette.io", blurb: "A CLI for screenshots, video demos and JavaScript-powered scraping." },
    ],
    experience: [],
    credentials: [],
  },
  "mitchellh-os": {
    identity: {
      name: "Mitchell Hashimoto",
      handle: "mitchellh",
      role: "Systems software developer",
      headline: "Building terminal, event-loop and developer infrastructure.",
      location: "Los Angeles, CA",
      available: false,
    },
    tagline: "Go, Zig, Nix and terminal systems from the co-founder of HashiCorp.",
    email: "",
    links: { github: "https://github.com/mitchellh", site: "https://mitchellh.com", x: "https://x.com/mitchellh" },
    stats: { contributionsPastYear: 7142, publicRepos: 106, featuredBuilds: 4, buildingSince: 2008 },
    stack: ["Go", "Zig", "Nix", "Nushell", "Ruby"],
    primaryStack: "Zig",
    disciplines: [["Systems", "Event loops and terminals"], ["Infrastructure", "Automation"], ["Tooling", "Developer workflows"]],
    projects: [
      { name: "mapstructure", year: 2024, tech: ["Go"], stars: 8036, repoUrl: "https://github.com/mitchellh/mapstructure", blurb: "A Go library for decoding generic maps into native structures and back." },
      { name: "vouch", year: 2026, tech: ["Nushell"], stars: 4976, repoUrl: "https://github.com/mitchellh/vouch", blurb: "A community trust-management system based on explicit vouches." },
      { name: "gox", year: 2023, tech: ["Go"], stars: 4580, repoUrl: "https://github.com/mitchellh/gox", blurb: "A simple, no-frills cross-compilation tool for Go." },
      { name: "libxev", year: 2026, tech: ["Zig", "C", "Wasm"], stars: 3538, repoUrl: "https://github.com/mitchellh/libxev", blurb: "A cross-platform high-performance event loop for Zig and C." },
    ],
    experience: [],
    credentials: [],
  },
  "Rich-Harris-brutalist": {
    identity: {
      name: "Rich Harris",
      handle: "Rich-Harris",
      role: "Software engineer and Svelte creator",
      headline: "Rethinking how the web builds user interfaces.",
      location: "New York City",
      available: false,
    },
    tagline: "Compilers, web frameworks, animation and focused developer tools.",
    email: "",
    links: { github: "https://github.com/Rich-Harris", site: "https://svelte.dev" },
    stats: { contributionsPastYear: 2925, publicRepos: 217, featuredBuilds: 4, buildingSince: 2011 },
    stack: ["JavaScript", "TypeScript", "Svelte", "CSS"],
    primaryStack: "JavaScript",
    disciplines: [["Frameworks", "Svelte"], ["Compilers", "Web tooling"], ["Interfaces", "Animation and interaction"]],
    projects: [
      { name: "svelte", year: 2026, tech: ["JavaScript", "Svelte"], stars: 87625, repoUrl: "https://github.com/sveltejs/svelte", demoUrl: "https://svelte.dev", blurb: "A compiler-driven UI framework for concise, efficient web development." },
      { name: "kit", year: 2026, tech: ["JavaScript", "Svelte"], stars: 20669, repoUrl: "https://github.com/sveltejs/kit", demoUrl: "https://svelte.dev/docs/kit", blurb: "Svelte's framework for streamlined full-stack web development." },
      { name: "degit", year: 2026, tech: ["TypeScript"], stars: 7896, repoUrl: "https://github.com/Rich-Harris/degit", blurb: "A straightforward project-scaffolding utility." },
      { name: "magic-string", year: 2025, tech: ["JavaScript"], stars: 2713, repoUrl: "https://github.com/Rich-Harris/magic-string", blurb: "A library for precise, source-map-aware string manipulation." },
    ],
    experience: [],
    credentials: [],
  },
  "addyosmani-paper-cinema": {
    identity: {
      name: "Addy Osmani",
      handle: "addyosmani",
      role: "Software engineer and author",
      headline: "Engineering performance, AI tooling and developer education.",
      location: "Sunnyvale, California",
      available: false,
    },
    tagline: "JavaScript performance, design patterns and production-grade tools for developers.",
    email: "",
    links: { github: "https://github.com/addyosmani", site: "https://www.addyosmani.com" },
    stats: { contributionsPastYear: 2874, publicRepos: 181, featuredBuilds: 4, buildingSince: 2009 },
    stack: ["JavaScript", "HTML", "CSS", "AI tooling"],
    primaryStack: "JavaScript",
    disciplines: [["Performance", "Critical rendering path"], ["Education", "Books and patterns"], ["AI tooling", "Agent skills"]],
    projects: [
      { name: "agent-skills", year: 2026, tech: ["JavaScript", "AI tooling"], stars: 78167, repoUrl: "https://github.com/addyosmani/agent-skills", blurb: "Production-grade engineering skills for AI coding agents." },
      { name: "critical", year: 2026, tech: ["JavaScript", "CSS"], stars: 10250, repoUrl: "https://github.com/addyosmani/critical", blurb: "A tool for extracting and inlining critical-path CSS in HTML pages." },
      { name: "backbone-fundamentals", year: 2024, tech: ["Rich Text Format", "JavaScript"], stars: 9182, repoUrl: "https://github.com/addyosmani/backbone-fundamentals", blurb: "A Creative Commons book covering Backbone.js from fundamentals to advanced use." },
      { name: "essential-js-design-patterns", year: 2021, tech: ["HTML", "JavaScript"], stars: 4910, repoUrl: "https://github.com/addyosmani/essential-js-design-patterns", blurb: "The source for Learning JavaScript Design Patterns." },
    ],
    experience: [],
    credentials: [],
  },
} satisfies Record<string, WorldData>;
